const SETSIDEMENU='SETSIDEMENU'
const CURRENTSELECTEDAUDIO='CURRENTSELECTEDAUDIO'
const CURRENTSELECTEDAUDIONAME='CURRENTSELECTEDAUDIONAME'


export{
    SETSIDEMENU,
    CURRENTSELECTEDAUDIO,
    CURRENTSELECTEDAUDIONAME,
}